config/routes.rb
Rails.application.routes.draw do
  get "/login", to: "sessions#new", as: :new_session
  resource :registrations, path: "signup", only: %w[ new create ]
  resource :session, except: %i[ new ]
  resources :events, path: "calendar"
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  root "static_pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user

  validates :name, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true

  validates :end_time, comparison: { greater_than: :start_time }
end

app/models/registration.rb
class Registration
  include ActiveModel::Model
  include ActiveModel::Attributes

  attribute :email_address, :string
  attribute :password, :string

  validates :email_address, presence: true
  validates :password, length: 6..128

  def save
    if valid?
      User.create!(email_address: email_address, password: password)
    end
  end

  def model_name
    ActiveModel::Name.new(self, nil, self.class.name)
  end
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy
  has_many :events, dependent: :destroy

  normalizes :email_address, with: ->(e) { e.strip.downcase }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    before_action :require_authentication
    helper_method :authenticated?
  end

  class_methods do
    def allow_unauthenticated_access(**options)
      skip_before_action :require_authentication, **options
    end
  end

  private
    def authenticated?
      resume_session
    end

    def require_authentication
      resume_session || request_authentication
    end

    def resume_session
      Current.session ||= find_session_by_cookie
    end

    def find_session_by_cookie
      Session.find_by(id: cookies.signed[:session_id]) if cookies.signed[:session_id]
    end

    def request_authentication
      session[:return_to_after_authenticating] = request.url
      redirect_to new_session_path
    end

    def after_authentication_url
      session.delete(:return_to_after_authenticating) || root_url
    end

    def start_new_session_for(user)
      user.sessions.create!(user_agent: request.user_agent, ip_address: request.remote_ip).tap do |session|
        Current.session = session
        cookies.signed.permanent[:session_id] = { value: session.id, httponly: true, same_site: :lax }
      end
    end

    def terminate_session
      Current.session.destroy
      cookies.delete(:session_id)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Current.user.events
    @sorted_events = Hash[]

    if params[:date]
      @focused_date = Time.at(params[:date].to_i).to_datetime.beginning_of_day
    else
      @focused_date = DateTime.now.beginning_of_day
    end

    for event in @events do
      if !@sorted_events[event.start_time.beginning_of_day.to_datetime]
        @sorted_events[event.start_time.beginning_of_day.to_datetime] = [ event ]
      else
        @sorted_events[event.start_time.beginning_of_day.to_datetime].push(event)
      end
    end
  end

  def new
    @event = Event.new
  end

  def edit
    res = Event.find(params[:id])
    if res.user == Current.user
      @event = res
    end
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params) && @event.user == Current.user
      redirect_to events_path
    else
      redirect_to update_event_path(@event)
    end
  end

  def create
    @event = Event.new(event_params)

    if Event.create(name: @event.name, start_time: @event.start_time, end_time: @event.end_time, user: Current.user)
      redirect_to events_path
    else
      @event.errors.full_messages
      redirect_to new_event_path
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_path
  end
private

  def event_params
    params.expect(event: [ :name, :start_time, :end_time ])
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  allow_unauthenticated_access
  before_action :set_user_by_token, only: %i[ edit update ]

  def new
  end

  def create
    if user = User.find_by(email_address: params[:email_address])
      PasswordsMailer.reset(user).deliver_later
    end

    redirect_to new_session_path, notice: "Password reset instructions sent (if user with that email address exists)."
  end

  def edit
  end

  def update
    if @user.update(params.permit(:password, :password_confirmation))
      redirect_to new_session_path, notice: "Password has been reset."
    else
      redirect_to edit_password_path(params[:token]), alert: "Passwords did not match."
    end
  end

  private
    def set_user_by_token
      @user = User.find_by_password_reset_token!(params[:token])
    rescue ActiveSupport::MessageVerifier::InvalidSignature
      redirect_to new_password_path, alert: "Password reset link is invalid or has expired."
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  allow_unauthenticated_access

  def new
    redirect_to "/calendar" if authenticated?

    @registration = Registration.new
  end

  def create
    @registration = Registration.new(registration_params)
    if user = @registration.save
      start_new_session_for user

      redirect_to root_url
    else
      redirect_to new_registrations_path
    end
  end

private

  def registration_params
    params.expect(registration: [ :email_address, :password ])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  allow_unauthenticated_access only: %i[ new create ]
  rate_limit to: 10, within: 3.minutes, only: :create, with: -> { redirect_to new_session_url, alert: "Try again later." }

  def new
  end

  def create
    if user = User.authenticate_by(params.permit(:email_address, :password))
      start_new_session_for user
      redirect_to "/calendar"
    else
      redirect_to new_session_path, alert: "Try another email address or password."
    end
  end

  def destroy
    terminate_session
    redirect_to new_session_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  allow_unauthenticated_access

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/events/edit.html.erb
<div
  class="
    h-[calc(100%-4rem)] flex flex-col items-center w-[clamp(350px,30vw,600px)]
    mx-auto px-4 bg-primary-content text-primary mt-16 rounded-2xl p-4
    place-content-center
  "
>
  <%= form_with model: @event, class: "w-full text-center text-neutral-content" do |form| %>
    <%= render partial: "partials/glow", locals: { text: "Edit Event!" } %>

    <hr class="mb-4">

    <label class="input input-bordered flex items-center gap-2 mb-8">
      <%= form.text_field :name,
                      required: true,
                      placeholder: "Event Name",
                      class: "w-full" %><br>
    </label>

    <div class="flex gap-2 mb-8 items-center">
      <p class="w-24">Start Time:</p>
      <label class="input input-bordered grow">
        <%= form.datetime_field :start_time, required: true, class: "w-full h-full" %>
      </label>
    </div>

    <div class="flex gap-2 mb-8 items-center">
      <p class="w-24">End Time:</p>
      <label class="input input-bordered grow">
        <%= form.datetime_field :end_time, required: true, class: "w-full h-full" %>
      </label>
    </div>

    <%= tag.div(flash[:alert], class: "text-error") if flash[:alert] %>
    <%= tag.div(flash[:notice], class: "text-success") if flash[:notice] %>
    <%= form.submit "Save", class: "btn btn-accent w-full mb-2" %>
  <% end %>
  <%= button_to "Delete", @event, method: :delete %>
</div>

app/views/events/index.html.erb
<div class="w-full h-full flex">
  <nav
    class="
      h-[calc(100%+4rem)] flex flex-col w-80 p-4 bg-base-300 overflow-scroll
    "
  >
    <div class="grid place-content-center">

      <%= render partial: "partials/glow",
      locals: {
        text: @focused_date.strftime("%e %b %Y"),
      } %>
    </div>
    <% for mon in 1..12 do %>
      <% if mon == @focused_date.month %>
        <p class="text-accent text-center text-lg border-t py-2"><%= @focused_date.strftime("%B") %></p>
        <table class="flex place-content-center w-full">
          <tbody class="grid">
            <tr class="grid grid-cols-[repeat(7,2rem)] h-8">
              <td class="grid place-content-center">M</td>
              <td class="grid place-content-center">T</td>
              <td class="grid place-content-center">W</td>
              <td class="grid place-content-center">T</td>
              <td class="grid place-content-center">F</td>
              <td class="grid place-content-center">S</td>
              <td class="grid place-content-center">S</td>
            </tr>
            <% counter = 0
            inner_counter = 1
            start_of_month = DateTime.new(@focused_date.year, @focused_date.month, 1)
            lengths = [
              31,
              28 + (Date.leap?(@focused_date.year) ? 1 : 0),
              31,
              30,
              31,
              30,
              31,
              31,
              30,
              31,
              30,
              31,
            ] %>
            <% while counter <= lengths[mon - 1] %>
              <tr class="grid grid-cols-[repeat(7,2rem)] h-8">
                <% while inner_counter < 8 %>
                  <% if counter == 0 && inner_counter < start_of_month.strftime("%u").to_i
                    inner_counter += 1
                  elsif counter == 0 && inner_counter == start_of_month.strftime("%u").to_i
                    counter += 1
                    inner_counter += 1
                  else
                    counter += 1
                    inner_counter += 1
                  end %>
                  <% if counter > 0 && counter <= lengths[mon - 1] %>
                    <td
                      class="
                        <%= counter == @focused_date.day ? "bg-primary rounded-full" : "" %> grid place-content-center
                      "
                    ><a
                        href="<%=events_path + "?date=" + DateTime.new(@focused_date.year, @focused_date.month, counter).to_time.to_i.to_s %>"
                      ><%= counter %></a></td>
                  <% else %>
                    <td></td>
                  <% end %>
                <% end %>
              </tr>
              <% inner_counter = 1 %>
            <% end %>
          </tbody>
        </table>
      <% else %>
        <a
          href="<%= events_path + "?date=" + DateTime.new(@focused_date.year, mon, 1).to_time.to_i.to_s %>"
          class="
            border-t text-lg text-center py-2 my-2 hover:text-primary transition-colors
            no-underline block
          "
        ><%= DateTime.new(0, mon, 1).strftime("%B") %></a>
      <% end %>
    <% end %>

    <div class="flex place-content-evenly">
      <a
        class = "hover:text-primary transition-colors"
        href = "<%= events_path + "?date=" + DateTime.new(@focused_date.year - 1, 1, 1).to_time.to_i.to_s%>"
      ><%= @focused_date.year - 1 %></a>
      <p class="text-secondary text-lg"><%= @focused_date.year %></p>
      <a
        class = "hover:text-primary transition-colors"
        href = "<%= events_path + "?date=" + DateTime.new(@focused_date.year + 1, 1, 1).to_time.to_i.to_s%>"
      ><%= @focused_date.year + 1 %></a>
    </div>
  </nav>

  <div class="grow h-full pt-16 px-8 flex place-content-center">
    <%= render partial: "partials/day",
    locals: {
      events: @sorted_events[@focused_date],
      start: @focused_date,
    } %>
  </div>

  <%= button_to "New",
  new_event_path,
  method: :get,
  class: "btn btn-accent w-80 absolute bottom-[-3.5rem] right-2" %>
</div>

app/views/events/new.html.erb
<div
  class="
    h-[calc(100%-4rem)] flex flex-col items-center w-[clamp(350px,30vw,600px)]
    mx-auto px-4 bg-primary-content text-primary mt-16 rounded-2xl p-4
    place-content-center
  "
>
  <%= form_with model: @event, class: "w-full text-center text-neutral-content" do |form| %>
    <%= render partial: "partials/glow", locals: { text: "New Event!" } %>

    <hr class="mb-4">

    <label class="input input-bordered flex items-center gap-2 mb-8">
      <%= form.text_field :name,
                      required: true,
                      placeholder: "Event Name",
                      class: "w-full" %><br>
    </label>

    <div class="flex gap-2 mb-8 items-center">
      <p class="w-24">Start Time:</p>
      <label class="input input-bordered grow">
        <%= form.datetime_field :start_time, required: true, class: "w-full h-full" %>
      </label>
    </div>

    <div class="flex gap-2 mb-8 items-center">
      <p class="w-24">End Time:</p>
      <label class="input input-bordered grow">
        <%= form.datetime_field :end_time, required: true, class: "w-full h-full" %>
      </label>
    </div>

    <%= tag.div(flash[:alert], class: "text-error") if flash[:alert] %>
    <%= tag.div(flash[:notice], class: "text-success") if flash[:notice] %>
    <%= form.submit "Create event", class: "btn btn-accent w-full mb-2" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Calendar" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
  </head>

  <body class="bg-base-200 w-screen h-screen">
    <div class=" fixed top-16 w-screen h-[calc(100vh-4rem)] ">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        xmlns:xlink="http://www.w3.org/1999/xlink"
        version="1.1"
        width="1080"
        height="1080"
        viewBox="0 0 1080 1080"
        xml:space="preserve"
        class="z-0 opacity-30"
      >
        <desc>Created with Fabric.js 5.2.4</desc>
        <defs>
        </defs>
        <g
          transform="matrix(1 0 0 1 540 540)"
          id="26902bc4-6cc5-474c-84f9-195c1637dced"
        >
          <rect
            style="stroke: none; stroke-width: 1; stroke-dasharray: none; stroke-linecap: butt; stroke-dashoffset: 0; stroke-linejoin: miter; stroke-miterlimit: 4; fill: var(--a); fill-rule: nonzero; opacity: 1; visibility: hidden;"
            vector-effect="non-scaling-stroke"
            x="-540"
            y="-540"
            rx="0"
            ry="0"
            width="1080"
            height="1080"
          />
        </g>
        <g
          transform="matrix(1 0 0 1 540 540)"
          id="19d268af-a0eb-4281-ad8f-7d4a323d49e2"
        >
        </g>
        <g
          transform="matrix(13.13 -13.13 0.71 0.71 509.41 591.25)"
          id="c4c9b06c-26d6-424a-8c46-2966ffe7b4ae"
        >
          <rect
            style="stroke: rgb(0,0,0); stroke-width: 0; stroke-dasharray: none; stroke-linecap: butt; stroke-dashoffset: 0; stroke-linejoin: miter; stroke-miterlimit: 4; fill: var(--fallback-a); fill: oklch(var(--a)); fill-rule: nonzero; opacity: 1;"
            vector-effect="non-scaling-stroke"
            x="-37.4585"
            y="-19.4165"
            rx="0"
            ry="0"
            width="74.917"
            height="45"
          />
        </g>
        <g
          transform="matrix(13.13 -13.13 0.71 0.71 12.48 652.01)"
          id="c4c9b06c-26d6-424a-8c46-2966ffe7b4ae"
        >
          <rect
            style="stroke: rgb(0,0,0); stroke-width: 0; stroke-dasharray: none; stroke-linecap: butt; stroke-dashoffset: 0; stroke-linejoin: miter; stroke-miterlimit: 4; fill: var(--fallback-a); fill: oklch(var(--a)); fill-rule: nonzero; opacity: 1;"
            vector-effect="non-scaling-stroke"
            x="-37.46"
            y="-19.415"
            rx="0"
            ry="0"
            width="74.92"
            height="15"
          />
        </g>
        <g
          transform="matrix(13.13 -13.13 0.71 0.71 488.18 811.42)"
          id="c4c9b06c-26d6-424a-8c46-2966ffe7b4ae"
        >
          <rect
            style="stroke: rgb(0,0,0); stroke-width: 0; stroke-dasharray: none; stroke-linecap: butt; stroke-dashoffset: 0; stroke-linejoin: miter; stroke-miterlimit: 4; fill: var(--fallback-in); fill: oklch(var(--in)); fill-rule: nonzero; opacity: 1;"
            vector-effect="non-scaling-stroke"
            x="-37.46"
            y="-19.415"
            rx="0"
            ry="0"
            width="74.92"
            height="35"
          />
        </g>
      </svg>
    </div>

    <nav
      class="
        navbar sticky top-0 z-40 h-16 px-8 text-base-content backdrop-blur bg-base-100
        bg-opacity-90 shadow-sm
      "
    >
      <%= link_to "CalendarApp", root_url, class: "flex-1 text-xl" %>
      <% if authenticated? %>
        <p class="mx-4"><%= Current.user.email_address %></p>
        <%= button_to "Log out", session_path, method: :delete, class: "btn btn-primary" %>
      <% else %>
        <%= button_to "Log in", new_session_path, method: :get, class: "btn btn-primary" %>
      <% end %>
    </nav>
    <main class="z-10 relative w-full h-[calc(100vh-8rem)]">
      <%= yield %>
    </main>
  </body>
</html>

app/views/partials/_day.html.erb
<div
  class="
    border rounded-2xl overflow-scroll scrollbar-none border-base-100 h-full w-96
    flex flex-col gap-6 p-2 relative
  "
>
  <% for h in 0..23 do %>
    <div class="flex gap-2 items-center">
      <p class="w-16"><%= "0" if h < 10 %><%= h %>:00</p>
      <hr class="w-full">
    </div>
  <% end %>

  <% if events != nil %>
    <% events.each do |event| %>
      <a href="<%= edit_event_path(event) %>">
        <div
          class="
            absolute w-[calc(100%-4.75rem)] top-0 bg-primary right-2 rounded-lg p-2
            overflow-scroll scrollbar-none
          "
          style="height: <%= ((event.end_time.to_i - event.start_time.to_i) / 1200)%>rem; top: <%= 1.25 + ((event.start_time.to_i - start.to_i) / 1200)%>rem;"
        >
          <%= event.name %>
        </div>
      </a>
    <% end %>
  <% end %>

</div>

app/views/partials/_glow.html.erb
<span class="inline-grid font-bold text-[clamp(1.5rem,3vw,2.1rem)] text-center">
  <span
    class="
      col-start-1 row-start-1
      bg-[linear-gradient(90deg,theme(colors.info)_0%,theme(colors.success)_9%,theme(colors.secondary)_42%,theme(colors.primary)_47%,theme(colors.accent)_100%)]
      bg-clip-text blur-xl [-webkit-text-fill-color:transparent]
      [transform:translate3d(0,0,0)] before:content-[attr(data-text)]
    "
    aria-hidden="true"
    data-text="<%= text %>"
  >
  </span>
  <span
    class="
      [&::selection]:text-base-content h-11 relative col-start-1 row-start-1
      bg-[linear-gradient(90deg,theme(colors.info)_0%,theme(colors.success)_9%,theme(colors.secondary)_42%,theme(colors.primary)_47%,theme(colors.accent)_100%)]
      bg-clip-text [-webkit-text-fill-color:transparent] [&::selection]:bg-blue-700/20
    "
  >
    <%= text %>
  </span>
</span>

app/views/static_pages/home.html.erb
<div class="w-full h-full grid place-content-center">
  <div class="flex flex-col items-center gap-2 max-w-96 text-center">
    <span class="inline-grid font-bold text-[clamp(1.5rem,3vw,2.1rem)] text-center">
      <span
        class="
          col-start-1 row-start-1
          bg-[linear-gradient(90deg,theme(colors.info)_0%,theme(colors.success)_9%,theme(colors.secondary)_42%,theme(colors.primary)_47%,theme(colors.accent)_100%)]
          bg-clip-text blur-xl [-webkit-text-fill-color:transparent]
          [transform:translate3d(0,0,0)] before:content-[attr(data-text)]
        "
        aria-hidden="true"
        data-text="CalendarApp"
      >
      </span>
      <span
        class="
          [&::selection]:text-base-content h-11 relative col-start-1 row-start-1
          bg-[linear-gradient(90deg,theme(colors.info)_0%,theme(colors.success)_9%,theme(colors.secondary)_42%,theme(colors.primary)_47%,theme(colors.accent)_100%)]
          bg-clip-text [-webkit-text-fill-color:transparent] [&::selection]:bg-blue-700/20
        "
      >
        CalendarApp
      </span>
    </span>
    <p>A simple app for managing your calendar, created using Ruby on Rails.
      Click the button below to get started!</p>
    <% if authenticated? %>
      <%= link_to "Your Calendar", "/calendar", class: "btn btn-primary" %>
    <% else %>
      <%= link_to "Sign Up", "/signup/new", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>